In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


In [9]:


arr = np.array(['apple', 'banana', 'cherry'],dtype='S6')
print(arr.dtype)


|S6


In [14]:



arr = np.array([1.2, 2.3, 3.4])

newarr = arr.astype(int) #int = 'i'
print(newarr)

[1 2 3]


In [17]:
arr = np.array([1,0,3,4,0])

newarr = arr.astype(bool)

print(newarr)

[ True False  True  True False]


In [18]:



arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [19]:
arr = np.array([1,2,3,4,5])

x = arr.view()

arr[0] = 43

print(arr)
print(x)

[43  2  3  4  5]
[43  2  3  4  5]


In [20]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [21]:



arr = np.array([1,2,3,4,5])
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [24]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [25]:




arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [27]:
#reshape array

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(3,4)
print(newarr)
print(newarr.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [28]:


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)
print(newarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


12


In [33]:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,9])

newarr = arr.reshape(3, 3)

print(newarr)



[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [44]:



arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,9,10,11,12])

newarr = arr.reshape(-1)

print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
