In [4]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
print(np.__version__)

1.25.1


# 0-D array
arr = np.array(10)
print(arr)
print(type(arr))

In [ ]:
#1-D array

arr = np.array([1,2,3,4,4])
print(arr)

In [ ]:
# 

In [ ]:
# 2-D array

arr = np.array([[1,2,3],[4,5,6]])
print(arr)


In [12]:
# 3-D array

arr = np.array([[[2,3,4,5,6],[1,2,3,4,5]],[[3,2,1,2,3],[5,3,2,1,2]]])

print(arr)


[[[2 3 4 5 6]
  [1 2 3 4 5]]

 [[3 2 1 2 3]
  [5 3 2 1 2]]]


In [13]:
#Check how many dimensions the arrays have:

print(arr.ndim)

3


In [15]:
# create an array with 5 dimensions and verify that it has 5 dimension

arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


In [19]:
#array indexing


arr = np.array([[2,3,2,1,4],[2,1,2,3,1]])

print(arr[0,3])

1


In [20]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])


6


In [21]:
# negative indexing
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])


Last element from 2nd dim:  10


In [23]:
#Slice elements 
arr = np.array([2,3,4,2,2,5,2,2])
print(arr[::2])

[2 4 2 2]


In [25]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:-1:2])

[1 3 5]


In [26]:
#2-D slicing


arr = np.array([[2,3,4,2],[6,8,9,0]])

print(arr[1,::2])

[6 9]


In [30]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]
